---
deployment:
  tasks:
    - export DEPLOYPATH=/data0/downloadlounge.com/public_html
    - /bin/chmod -R 755 $DEPLOYPATH/downloadloungecom || true
    - /bin/cp -rf downloadlounge.com/. $DEPLOYPATH/downloadloungecom/
